### PR TITLE
Modify CellType to support properties

### PR DESCRIPTION
**Pull request by budnyric**
Adds a std::set containing std::strings respresenting binary properties
Adds methods SetProperty,RemoveProperty,HasProperty. SetProperty and RemoveProperty can be chained
Adds one constant CELL_WALL to cell type (this marks tiles that are impassible).
Modifies MazeWorld to use properties instead of saved ids for traversal check
Adds tests for CellType property methods.

All tests were passing and MazeWorld behaved as expected when I tested locally.

### CODE REVIEW

**Review by ravipat3 — COMMENTED** [review]
This looks good!

Make sure to add water as a property soon!

**Review by FergusonAJ — APPROVED** [review]
Looks like a solid simple change that improves functionality. 
Using constexpr strings for properties used across groups is a nice idea! 
Approved.

**Comment by FergusonAJ** [comment]
Ah, there is the question of if this should go into `development` before `main`. We've never formalized the process for that...

**Comment by budnyric** [comment]
> Ah, there is the question of if this should go into `development` before `main`. We've never formalized the process for that...

Initially this was merged into development branch - I changed it when development merged in because I had been trying to get it in with that set of changes. I could change it back if that was more useful.

**Pull request merged**
