### PR TITLE
just added texture for the new assets

### PR DESCRIPTION
**Pull request by Gaya1858**

### CODE REVIEW

**Comment by Gaya1858** [comment]
Just added some texture loader for new assets

**Review by Gaya1858 — COMMENTED** [review]
Just added texture holders for newly added assets by group6

**Comment by Gaya1858** [comment]
Hi Vince, Can you approve this pull request. I just added some assets to the texture holder.

**Review by Felicivi — APPROVED** [review]
There's new texture files and code cleanup

**Pull request merged**
