### PR TITLE
Add CMake with SFML support

### PR DESCRIPTION
**Pull request by FergusonAJ**
This expands off @amantham20 's PR (#20)
It adds SFML as a git submodule, and swaps `sample_main.cpp` with `sfml_main.cpp` so folks have a minimum example to test if SFML is working correctly. 

Note that Windows and Mac users should be able to compile SFML without any other dependencies. 
Linux users will need to install the following packages, including development headers: 
- freetype
- x11
- xrandr
- udev
- opengl
- flac
- ogg
- vorbis
- vorbisenc
- vorbisfile
- openal
- pthread

The following setups have been confirmed to work (albeit they may require a little extra configuration): 
- g++12 on PopOS 22.04
- MinGW via VSCode terminal on Windows 10
- MinGW via CLion on Windows 10

closes #20

### CODE REVIEW

**Comment by FergusonAJ** [comment]
Possible things to look into in the future: 
- Separating testing executables into a separate (sub) directory as to not clog up the main binary directory
- Retooling tests CMakeLists to also include SFML, so SFML-based files can also be tested

But for now, I'd argue it's more important to get to a point where everyone can compile the code

**Comment by amantham20** [comment]
closes #20

**Review by mercere99 — COMMENTED** [review]
Added CMake build system and SFML submodule, as well as a HowToCompile.md documentation file.

* How to should be linked in to README.md
* sfml_main.cpp should be renamed to something that doesn't look like a project main file, perhaps sfml_exmaple.cpp
* Changes should be rolled back to old-style Makefile (which will be depricated)
* Add documentation support of alternate modes of compilation, such as debug.

**Review by mercere99 — APPROVED** [review]
All changes now look good!

**Pull request merged**
